name = "toeic-drill-worker"
main = "worker/index.ts"
compatibility_date = "2024-09-10"
workers_dev = true

[[kv_namespaces]]
binding = "STATE_KV"
id = "a673f0aa8ead4e418fe952cf11dbc940"
preview_id = "209807235a9740e491266bbc1c79fb72"
